# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled_new.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1406, 881)
        Form.setMinimumSize(QtCore.QSize(600, 600))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.groupBox_5 = QtWidgets.QGroupBox(Form)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.groupBox_12 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_12.setObjectName("groupBox_12")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_12)
        self.gridLayout.setObjectName("gridLayout")
        self.radioButton_8 = QtWidgets.QRadioButton(self.groupBox_12)
        self.radioButton_8.setObjectName("radioButton_8")
        self.gridLayout.addWidget(self.radioButton_8, 0, 0, 1, 1)
        self.radioButton_7 = QtWidgets.QRadioButton(self.groupBox_12)
        self.radioButton_7.setObjectName("radioButton_7")
        self.gridLayout.addWidget(self.radioButton_7, 0, 2, 1, 1)
        self.radioButton_6 = QtWidgets.QRadioButton(self.groupBox_12)
        self.radioButton_6.setObjectName("radioButton_6")
        self.gridLayout.addWidget(self.radioButton_6, 2, 0, 1, 1)
        self.radioButton_10 = QtWidgets.QRadioButton(self.groupBox_12)
        self.radioButton_10.setObjectName("radioButton_10")
        self.gridLayout.addWidget(self.radioButton_10, 2, 2, 1, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_12)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout.addWidget(self.radioButton_2, 3, 0, 1, 1)
        self.horizontalLayout_10.addWidget(self.groupBox_12)
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.radioButton_15 = QtWidgets.QRadioButton(self.groupBox_8)
        self.radioButton_15.setObjectName("radioButton_15")
        self.gridLayout_3.addWidget(self.radioButton_15, 0, 0, 1, 1)
        self.radioButton_16 = QtWidgets.QRadioButton(self.groupBox_8)
        self.radioButton_16.setObjectName("radioButton_16")
        self.gridLayout_3.addWidget(self.radioButton_16, 1, 0, 1, 1)
        self.radioButton_14 = QtWidgets.QRadioButton(self.groupBox_8)
        self.radioButton_14.setObjectName("radioButton_14")
        self.gridLayout_3.addWidget(self.radioButton_14, 0, 1, 1, 1)
        self.radioButton_17 = QtWidgets.QRadioButton(self.groupBox_8)
        self.radioButton_17.setObjectName("radioButton_17")
        self.gridLayout_3.addWidget(self.radioButton_17, 1, 1, 1, 1)
        self.horizontalLayout_10.addWidget(self.groupBox_8)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.radioButton_11 = QtWidgets.QRadioButton(self.groupBox_6)
        self.radioButton_11.setObjectName("radioButton_11")
        self.verticalLayout_7.addWidget(self.radioButton_11)
        self.radioButton_9 = QtWidgets.QRadioButton(self.groupBox_6)
        self.radioButton_9.setObjectName("radioButton_9")
        self.verticalLayout_7.addWidget(self.radioButton_9)
        self.radioButton_12 = QtWidgets.QRadioButton(self.groupBox_6)
        self.radioButton_12.setObjectName("radioButton_12")
        self.verticalLayout_7.addWidget(self.radioButton_12)
        self.horizontalLayout_10.addWidget(self.groupBox_6)
        self.groupBox_10 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_10.setObjectName("groupBox_10")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.radioButton_23 = QtWidgets.QRadioButton(self.groupBox_10)
        self.radioButton_23.setObjectName("radioButton_23")
        self.verticalLayout_6.addWidget(self.radioButton_23)
        self.radioButton_22 = QtWidgets.QRadioButton(self.groupBox_10)
        self.radioButton_22.setObjectName("radioButton_22")
        self.verticalLayout_6.addWidget(self.radioButton_22)
        self.radioButton_24 = QtWidgets.QRadioButton(self.groupBox_10)
        self.radioButton_24.setObjectName("radioButton_24")
        self.verticalLayout_6.addWidget(self.radioButton_24)
        self.horizontalLayout_10.addWidget(self.groupBox_10)
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.radioButton_27 = QtWidgets.QRadioButton(self.groupBox_9)
        self.radioButton_27.setObjectName("radioButton_27")
        self.verticalLayout_3.addWidget(self.radioButton_27)
        self.radioButton_26 = QtWidgets.QRadioButton(self.groupBox_9)
        self.radioButton_26.setObjectName("radioButton_26")
        self.verticalLayout_3.addWidget(self.radioButton_26)
        self.radioButton_28 = QtWidgets.QRadioButton(self.groupBox_9)
        self.radioButton_28.setObjectName("radioButton_28")
        self.verticalLayout_3.addWidget(self.radioButton_28)
        self.horizontalLayout_10.addWidget(self.groupBox_9)
        self.groupBox_14 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_14.setObjectName("groupBox_14")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_14)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioButton_20 = QtWidgets.QRadioButton(self.groupBox_14)
        self.radioButton_20.setObjectName("radioButton_20")
        self.verticalLayout_2.addWidget(self.radioButton_20)
        self.radioButton_21 = QtWidgets.QRadioButton(self.groupBox_14)
        self.radioButton_21.setObjectName("radioButton_21")
        self.verticalLayout_2.addWidget(self.radioButton_21)
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_14)
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout_2.addWidget(self.radioButton_3)
        self.horizontalLayout_10.addWidget(self.groupBox_14)
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.radioButton_31 = QtWidgets.QRadioButton(self.groupBox_7)
        self.radioButton_31.setObjectName("radioButton_31")
        self.verticalLayout_4.addWidget(self.radioButton_31)
        self.radioButton_30 = QtWidgets.QRadioButton(self.groupBox_7)
        self.radioButton_30.setObjectName("radioButton_30")
        self.verticalLayout_4.addWidget(self.radioButton_30)
        self.radioButton_32 = QtWidgets.QRadioButton(self.groupBox_7)
        self.radioButton_32.setObjectName("radioButton_32")
        self.verticalLayout_4.addWidget(self.radioButton_32)
        self.horizontalLayout_10.addWidget(self.groupBox_7)
        self.groupBox_11 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_11.setObjectName("groupBox_11")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_11)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.radioButton_19 = QtWidgets.QRadioButton(self.groupBox_11)
        self.radioButton_19.setObjectName("radioButton_19")
        self.verticalLayout_5.addWidget(self.radioButton_19)
        self.radioButton_18 = QtWidgets.QRadioButton(self.groupBox_11)
        self.radioButton_18.setObjectName("radioButton_18")
        self.verticalLayout_5.addWidget(self.radioButton_18)
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_11)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout_5.addWidget(self.radioButton)
        self.horizontalLayout_10.addWidget(self.groupBox_11)
        self.gridLayout_8.addWidget(self.groupBox_5, 5, 0, 1, 2)
        self.groupBox_13 = QtWidgets.QGroupBox(Form)
        self.groupBox_13.setObjectName("groupBox_13")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_13)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox_13)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_6.addWidget(self.textEdit)
        self.textEdit_2 = QtWidgets.QTextEdit(self.groupBox_13)
        self.textEdit_2.setObjectName("textEdit_2")
        self.horizontalLayout_6.addWidget(self.textEdit_2)
        self.gridLayout_8.addWidget(self.groupBox_13, 7, 0, 1, 2)
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_3.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_3.addWidget(self.pushButton_5)
        self.gridLayout_8.addWidget(self.groupBox_3, 2, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout.addWidget(self.lineEdit_2)
        self.gridLayout_8.addWidget(self.groupBox, 0, 0, 1, 2)
        self.groupBox_4 = QtWidgets.QGroupBox(Form)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_8.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_7.addWidget(self.lineEdit_4)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_7.addWidget(self.lineEdit_5)
        self.progressBar = QtWidgets.QProgressBar(self.groupBox_4)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_7.addWidget(self.progressBar)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_7)
        self.gridLayout_8.addWidget(self.groupBox_4, 6, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setMinimumSize(QtCore.QSize(240, 320))
        self.label.setMaximumSize(QtCore.QSize(480, 640))
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setMinimumSize(QtCore.QSize(240, 320))
        self.label_2.setMaximumSize(QtCore.QSize(480, 640))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.gridLayout_8.addWidget(self.groupBox_2, 1, 0, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout_8)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox_5.setTitle(_translate("Form", "Label"))
        self.groupBox_12.setTitle(_translate("Form", "人种"))
        self.radioButton_8.setText(_translate("Form", "中国人（典型亚裔面孔)"))
        self.radioButton_7.setText(_translate("Form", "中国的少数民族（包括新疆人等）"))
        self.radioButton_6.setText(_translate("Form", "东南亚人"))
        self.radioButton_10.setText(_translate("Form", "不统一"))
        self.radioButton_2.setText(_translate("Form", "中东人"))
        self.groupBox_8.setTitle(_translate("Form", "年龄"))
        self.radioButton_15.setText(_translate("Form", "青少年"))
        self.radioButton_16.setText(_translate("Form", "中老年"))
        self.radioButton_14.setText(_translate("Form", "中年人"))
        self.radioButton_17.setText(_translate("Form", "不统一"))
        self.groupBox_6.setTitle(_translate("Form", "性别"))
        self.radioButton_11.setText(_translate("Form", "男"))
        self.radioButton_9.setText(_translate("Form", "女"))
        self.radioButton_12.setText(_translate("Form", "不统一"))
        self.groupBox_10.setTitle(_translate("Form", "眼镜"))
        self.radioButton_23.setText(_translate("Form", "戴眼镜"))
        self.radioButton_22.setText(_translate("Form", "不戴眼镜"))
        self.radioButton_24.setText(_translate("Form", "不统一"))
        self.groupBox_9.setTitle(_translate("Form", "帽子"))
        self.radioButton_27.setText(_translate("Form", "戴帽子"))
        self.radioButton_26.setText(_translate("Form", "不戴帽子"))
        self.radioButton_28.setText(_translate("Form", "不统一"))
        self.groupBox_14.setTitle(_translate("Form", "刘海"))
        self.radioButton_20.setText(_translate("Form", "有刘海"))
        self.radioButton_21.setText(_translate("Form", "无刘海"))
        self.radioButton_3.setText(_translate("Form", "不统一"))
        self.groupBox_7.setTitle(_translate("Form", "是否化妆"))
        self.radioButton_31.setText(_translate("Form", "有"))
        self.radioButton_30.setText(_translate("Form", "无"))
        self.radioButton_32.setText(_translate("Form", "不统一"))
        self.groupBox_11.setTitle(_translate("Form", "发型"))
        self.radioButton_19.setText(_translate("Form", "有"))
        self.radioButton_18.setText(_translate("Form", "无"))
        self.radioButton.setText(_translate("Form", "不统一"))
        self.groupBox_13.setTitle(_translate("Form", "DetailInfo"))
        self.groupBox_3.setTitle(_translate("Form", "Operating"))
        self.pushButton_2.setText(_translate("Form", "上一张"))
        self.pushButton_3.setText(_translate("Form", "下一张"))
        self.pushButton_4.setText(_translate("Form", "跳过"))
        self.pushButton_5.setText(_translate("Form", "保存"))
        self.groupBox.setTitle(_translate("Form", "Category"))
        # self.lineEdit.setText(_translate("Form", "                                 抓拍照"))
        # self.lineEdit_2.setText(_translate("Form", "                                 1vn底图"))
        self.groupBox_4.setTitle(_translate("Form", "Schedule"))
        self.groupBox_2.setTitle(_translate("Form", "Image"))
        self.label.setText(_translate("Form", "TextLabel"))
        self.label_2.setText(_translate("Form", "TextLabel"))
