# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1359, 901)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(20, 630, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(180, 630, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(330, 630, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(0, 770, 641, 131))
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(40, 30, 381, 561))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(470, 30, 391, 561))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(910, 30, 381, 561))
        self.label_3.setObjectName("label_3")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(480, 630, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(0, 680, 181, 70))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_7 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_7.setObjectName("checkBox_7")
        self.gridLayout.addWidget(self.checkBox_7, 0, 1, 1, 1)
        self.checkBox_8 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_8.setObjectName("checkBox_8")
        self.gridLayout.addWidget(self.checkBox_8, 0, 0, 1, 1)
        self.checkBox_6 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_6.setObjectName("checkBox_6")
        self.gridLayout.addWidget(self.checkBox_6, 1, 0, 1, 1)
        self.checkBox_10 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_10.setObjectName("checkBox_10")
        self.gridLayout.addWidget(self.checkBox_10, 1, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(190, 680, 181, 70))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.checkBox_9 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_9.setObjectName("checkBox_9")
        self.gridLayout_2.addWidget(self.checkBox_9, 0, 1, 1, 1)
        self.checkBox_11 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_11.setObjectName("checkBox_11")
        self.gridLayout_2.addWidget(self.checkBox_11, 0, 0, 1, 1)
        self.checkBox_12 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_12.setObjectName("checkBox_12")
        self.gridLayout_2.addWidget(self.checkBox_12, 1, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setGeometry(QtCore.QRect(380, 680, 181, 70))
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.checkBox_15 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_15.setObjectName("checkBox_15")
        self.gridLayout_3.addWidget(self.checkBox_15, 0, 0, 1, 1)
        self.checkBox_16 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_16.setObjectName("checkBox_16")
        self.gridLayout_3.addWidget(self.checkBox_16, 1, 0, 1, 1)
        self.checkBox_17 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_17.setObjectName("checkBox_17")
        self.gridLayout_3.addWidget(self.checkBox_17, 1, 1, 1, 1)
        self.checkBox_14 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_14.setObjectName("checkBox_14")
        self.gridLayout_3.addWidget(self.checkBox_14, 0, 1, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(Form)
        self.groupBox_4.setGeometry(QtCore.QRect(1140, 670, 211, 101))
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_4.addWidget(self.checkBox, 3, 0, 1, 1)
        self.checkBox_18 = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_18.setObjectName("checkBox_18")
        self.gridLayout_4.addWidget(self.checkBox_18, 0, 0, 1, 1)
        self.checkBox_19 = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_19.setObjectName("checkBox_19")
        self.gridLayout_4.addWidget(self.checkBox_19, 0, 1, 1, 1)
        self.checkBox_21 = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_21.setObjectName("checkBox_21")
        self.gridLayout_4.addWidget(self.checkBox_21, 1, 1, 1, 1)
        self.checkBox_20 = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_20.setObjectName("checkBox_20")
        self.gridLayout_4.addWidget(self.checkBox_20, 1, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(Form)
        self.groupBox_5.setGeometry(QtCore.QRect(570, 680, 181, 70))
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.checkBox_22 = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_22.setObjectName("checkBox_22")
        self.gridLayout_5.addWidget(self.checkBox_22, 0, 1, 1, 1)
        self.checkBox_23 = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_23.setObjectName("checkBox_23")
        self.gridLayout_5.addWidget(self.checkBox_23, 0, 0, 1, 1)
        self.checkBox_24 = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_24.setObjectName("checkBox_24")
        self.gridLayout_5.addWidget(self.checkBox_24, 1, 0, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(Form)
        self.groupBox_6.setGeometry(QtCore.QRect(760, 680, 181, 70))
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.checkBox_26 = QtWidgets.QCheckBox(self.groupBox_6)
        self.checkBox_26.setObjectName("checkBox_26")
        self.gridLayout_6.addWidget(self.checkBox_26, 0, 1, 1, 1)
        self.checkBox_27 = QtWidgets.QCheckBox(self.groupBox_6)
        self.checkBox_27.setObjectName("checkBox_27")
        self.gridLayout_6.addWidget(self.checkBox_27, 0, 0, 1, 1)
        self.checkBox_28 = QtWidgets.QCheckBox(self.groupBox_6)
        self.checkBox_28.setObjectName("checkBox_28")
        self.gridLayout_6.addWidget(self.checkBox_28, 1, 0, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(Form)
        self.groupBox_7.setGeometry(QtCore.QRect(950, 680, 181, 70))
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.checkBox_30 = QtWidgets.QCheckBox(self.groupBox_7)
        self.checkBox_30.setObjectName("checkBox_30")
        self.gridLayout_7.addWidget(self.checkBox_30, 0, 1, 1, 1)
        self.checkBox_31 = QtWidgets.QCheckBox(self.groupBox_7)
        self.checkBox_31.setObjectName("checkBox_31")
        self.gridLayout_7.addWidget(self.checkBox_31, 0, 0, 1, 1)
        self.checkBox_32 = QtWidgets.QCheckBox(self.groupBox_7)
        self.checkBox_32.setObjectName("checkBox_32")
        self.gridLayout_7.addWidget(self.checkBox_32, 1, 0, 1, 1)
        self.textEdit_2 = QtWidgets.QTextEdit(Form)
        self.textEdit_2.setGeometry(QtCore.QRect(650, 770, 701, 131))
        self.textEdit_2.setObjectName("textEdit_2")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(620, 630, 75, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(170, 10, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(610, 10, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(1040, 10, 113, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(Form)
        self.lineEdit_4.setGeometry(QtCore.QRect(830, 630, 113, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(Form)
        self.lineEdit_5.setGeometry(QtCore.QRect(1040, 630, 113, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "打开"))
        self.pushButton_2.setText(_translate("Form", "上一张"))
        self.pushButton_3.setText(_translate("Form", "下一张"))
        self.label.setText(_translate("Form", "TextLabel"))
        self.label_2.setText(_translate("Form", "TextLabel"))
        self.label_3.setText(_translate("Form", "TextLabel"))
        self.pushButton_4.setText(_translate("Form", "跳过"))
        self.groupBox.setTitle(_translate("Form", "人种"))
        self.checkBox_7.setText(_translate("Form", "非典型亚裔面孔"))
        self.checkBox_8.setText(_translate("Form", "中国人"))
        self.checkBox_6.setText(_translate("Form", "少数民族"))
        self.checkBox_10.setText(_translate("Form", "其他"))
        self.groupBox_2.setTitle(_translate("Form", "性别"))
        self.checkBox_9.setText(_translate("Form", "女"))
        self.checkBox_11.setText(_translate("Form", "男"))
        self.checkBox_12.setText(_translate("Form", "其他"))
        self.groupBox_3.setTitle(_translate("Form", "年龄"))
        self.checkBox_15.setText(_translate("Form", "青少年"))
        self.checkBox_16.setText(_translate("Form", "中老年"))
        self.checkBox_17.setText(_translate("Form", "其他"))
        self.checkBox_14.setText(_translate("Form", "中年人"))
        self.groupBox_4.setTitle(_translate("Form", "发型"))
        self.checkBox.setText(_translate("Form", "其他"))
        self.checkBox_18.setText(_translate("Form", "短发"))
        self.checkBox_19.setText(_translate("Form", "长发"))
        self.checkBox_21.setText(_translate("Form", "无刘海"))
        self.checkBox_20.setText(_translate("Form", "有刘海"))
        self.groupBox_5.setTitle(_translate("Form", "眼镜"))
        self.checkBox_22.setText(_translate("Form", "不戴眼镜"))
        self.checkBox_23.setText(_translate("Form", "戴眼镜"))
        self.checkBox_24.setText(_translate("Form", "其他"))
        self.groupBox_6.setTitle(_translate("Form", "帽子"))
        self.checkBox_26.setText(_translate("Form", "不戴帽子"))
        self.checkBox_27.setText(_translate("Form", "戴帽子"))
        self.checkBox_28.setText(_translate("Form", "其他"))
        self.groupBox_7.setTitle(_translate("Form", "是否化妆"))
        self.checkBox_30.setText(_translate("Form", "没化妆"))
        self.checkBox_31.setText(_translate("Form", "化妆"))
        self.checkBox_32.setText(_translate("Form", "其他"))
        self.pushButton_5.setText(_translate("Form", "保存"))
        self.lineEdit.setText(_translate("Form", "      serial"))
        self.lineEdit_2.setText(_translate("Form", "       1v1"))
        self.lineEdit_3.setText(_translate("Form", "       1vn"))
